{{- if .Values.etcd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-assistant.fullname" . }}-etcd
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rag-assistant.labels" . | nindent 4 }}
    component: etcd
spec:
  replicas: {{ .Values.etcd.replicaCount }}
  selector:
    matchLabels:
      {{- include "rag-assistant.selectorLabels" . | nindent 6 }}
      component: etcd
  template:
    metadata:
      labels:
        {{- include "rag-assistant.selectorLabels" . | nindent 8 }}
        component: etcd
    spec:
      containers:
      - name: etcd
        image: "{{ .Values.etcd.image.repository }}:{{ .Values.etcd.image.tag }}"
        imagePullPolicy: {{ .Values.etcd.image.pullPolicy }}
        ports:
        - name: client
          containerPort: 2379
          protocol: TCP
        - name: peer
          containerPort: 2380
          protocol: TCP
        env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ETCD_SNAPSHOT_COUNT
          value: "50000"
        command:
          - etcd
          - --advertise-client-urls=http://0.0.0.0:2379
          - --listen-client-urls=http://0.0.0.0:2379
          - --data-dir=/etcd
        volumeMounts:
        {{- if .Values.etcd.persistence.enabled }}
        - name: etcd-data
          mountPath: /etcd
        {{- end }}
      volumes:
      {{- if .Values.etcd.persistence.enabled }}
      - name: etcd-data
        persistentVolumeClaim:
          claimName: {{ include "rag-assistant.fullname" . }}-etcd
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-assistant.fullname" . }}-etcd
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rag-assistant.labels" . | nindent 4 }}
    component: etcd
spec:
  type: {{ .Values.etcd.service.type }}
  ports:
    - name: client
      port: {{ .Values.etcd.service.port }}
      targetPort: client
      protocol: TCP
  selector:
    {{- include "rag-assistant.selectorLabels" . | nindent 4 }}
    component: etcd
{{- if .Values.etcd.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rag-assistant.fullname" . }}-etcd
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rag-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.etcd.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.etcd.persistence.size }}
{{- end }}
{{- end }}
