{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rag-assistant.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rag-assistant.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rag-assistant.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rag-assistant.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rag-assistant.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rag-assistant.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
{{- end }}
