apiVersion: v2
name: rag-assistant
description: KubeSphere RAG Assistant Extension Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubesphere
  - extension
  - rag
  - ai
  - llm
home: https://github.com/jia17/llm-milvus-api
sources:
  - https://github.com/jia17/llm-milvus-api
maintainers:
  - name: Zhang Jia
    email: jia337791@gmail.com
icon: https://raw.githubusercontent.com/kubesphere/rag-extension/main/docs/images/logo.png
dependencies: []
